### ISSUE TITLE
Question: Is it possible to stream an audio file?

### ISSUE THREAD

**Issue by SamTV12345** [jofas/actix_proxy#7]
I'd like to stream an audio file from a podcast server. I currently have the problem that my code is not working. Maybe you could add the functionality to stream audio from a podcast where I simply take the request from my frontend and convert it into a request to the podcast server and then returning that streamed body to my frontend again.

If you need a podcast url you can find an example [here](https://adswizz.podigee-cdn.net/version/1679607802/media/podcast_59711_die_nervigen_episode_1054673_38_kasefuss_kuss_mit_zitterlippe.mp3?awCollectionId=svo_4b3edb&awEpisodeId=1054673&v=1679607802&listeningSessionID=0CD_382_128__129e267060d8024e9a7f254815bedb1baba6d84a). The server does not insert cors headers so direct streaming is not possible.
 

```rust
pub(crate) async fn proxy_podcast(
    req: HttpRequest,
    payload: web::Payload,
    method: Method,
    params: web::Query<Params>
) -> HttpResponse {
    let new_url = params.url.clone();

    let mut forwarded_req = AwcClient::new()
        .request_from(new_url.clone(),req.head())
        .timeout(Duration::from_secs(10))
        .no_decompress();

    req.headers().iter().for_each(|(header_name, header_value)| {
        forwarded_req.headers_mut().append(header_name.clone(), header_value.clone());
    });

    let res = forwarded_req
        .send_stream(payload)
        .await;

    if res.is_err() {
        return HttpResponse::InternalServerError().json("Error proxying podcast");
    }

    let unwrapped_res = res.unwrap();
    let mut client_resp = HttpResponse::build(unwrapped_res.status());
    for (header_name, header_value) in unwrapped_res.headers().iter().filter(|(h, _)| *h != "connection") {
        client_resp.insert_header((header_name.clone(), header_value.clone()));
    }

    let streaming_res = client_resp.streaming(unwrapped_res);
    if streaming_res.status()==400{
        return HttpResponse::PermanentRedirect().append_header((LOCATION,new_url)).finish()
    }
    streaming_res
}
```

**Comment by SamTV12345** [comment]
Great. Thank you for adding that to your test suite. I noticed that you need to adapt the headers so the streaming website doesn't try to redirect to its site:

```rust
for x in rq.headers() {
        if x.0 == "host"||x.0 == "referer"||x.0 == "sec-fetch-site"||x.0 == "sec-fetch-mode" {
            continue;
        }
        header_map.append(x.0.clone(), x.1.clone());
    }

    // Required to not generate a 302 redirect
    header_map.append("sec-fetch-mode", "no-cors".parse().unwrap());
    header_map.append("sec-fetch-site", "cross-site".parse().unwrap());
    ```

**Comment by jofas** [comment]
Okay, but wouldn't something like this work:

```rust
async fn streaming_proxy( 
  client: web::Data<Client>, 
) -> actix_web::Result<HttpResponse, SendRequestError> { 
  let mut res = client 
    .get(STREAMING_URL) 
    .send() 
    .await?;

  let mut headers = res.headers_mut();

  headers.remove("host");
  headers.remove("referer");
  headers.remove("sec-fetch-site");
  headers.remove("sec-fetch-mode");
    
  headers.insert("sec-fetch-mode", "no-cors".parse().unwrap());
  headers.insert("sec-fetch-site", "cross-site".parse().unwrap());

  Ok(res)
} 
```

**Comment by SamTV12345** [comment]
That should not work as the podcast server doesn't know anything about the range it should request like [Content Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) or [Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) that are used to tell the server which bytes of the audio you need.

**Comment by jofas** [comment]
So your proxy gets a request from a client with the `Range` or `Content-Range` headers set and you want to forward it to your podcast server and then stream the answer back to your client, right? That is indeed not possible with `actix-proxy` out-of-the-box right now, as this library does not support converting a `actix::HttpRequest` to an `awc::ClientRequest`, only vice versa. This would be a great feature indeed!

**Comment by jofas** [comment]
During implementing a conversion trait from `actix_web::HttpRequest` to `awc::ClientRequest` and re-reading your first post, I realized that this is actually supported out-of-the-box in `awc` with the [`awc::Client::request_from`](https://docs.rs/awc/latest/awc/struct.Client.html#method.request_from) method. Would something like this work in your case:

```rust
async fn proxy_podcast(
    req: HttpRequest,
    client: web::Data<Client>, 
    params: web::Query<Params>,
    payload: web::Payload,
) -> actix_web::Result<HttpResponse, SendRequestError> { 
    let mut res = client 
        .from_request(params.url, req.head())
        .send_stream(payload) 
        .await?
        .into_http_response();

    let mut headers = res.headers_mut();

    headers.remove("host");
    headers.remove("referer");
    headers.remove("sec-fetch-site");
    headers.remove("sec-fetch-mode");
    
    headers.insert("sec-fetch-mode", "no-cors".parse().unwrap());
    headers.insert("sec-fetch-site", "cross-site".parse().unwrap());

    Ok(res)
} 
```

**Comment by SamTV12345** [comment]
You can even add the method to the client. Just pass method:Method in the parameters of the function.

**Comment by jofas** [comment]
Actually, if you look at the [source](https://docs.rs/awc/latest/src/awc/client/mod.rs.html#107-117) of `Client::request_from`, it does set the method automatically, extracting it from the headers.
